# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: armada_db
  host: localhost
  user: itorresverdugo
  pool: 5
  timeout: 5000